In [1]:
import numpy as np

In [2]:
data = np.random.randn(10)
y = np.where(data<0, 0, 1)

In [3]:
data

array([-0.11412998, -0.18636574, -1.7358172 ,  0.00701037, -0.35036055,
        0.76852993, -0.4241074 , -0.13082829, -0.54665069,  1.3638287 ])

In [4]:
y

array([0, 0, 0, 1, 0, 1, 0, 0, 0, 1])

In [5]:
def sigmoid(x):
    return (1 / (1 + np.exp(-x)))

In [6]:
def model(weight, bias, x):
    return weight*x + bias

In [7]:
np.random.seed(0)
W1 = np.random.randn(1)
b1 = np.random.randn(1)

In [8]:
y_pred = model(W1.item(), b1.item(), data)

In [9]:
y_pred

array([ 0.19882595,  0.07139828, -2.6619152 ,  0.41252386, -0.21789714,
        1.75588424, -0.34799044,  0.16936926, -0.56416323,  2.80602242])

#### Converting from linear to non-linear

In [10]:
z = sigmoid(y_pred)

In [11]:
z

array([0.54954338, 0.51784199, 0.06525841, 0.6016929 , 0.44574023,
       0.85269344, 0.41386982, 0.54224139, 0.36258472, 0.9430004 ])

#### Logarithimic Loss

In [12]:
def binary_cross_entropy(y_pred, y_true):
    return -(y_true * np.log(y_pred) + (1 - y_true) * np.log(1 - y_pred)).mean()

In [13]:
loss = binary_cross_entropy(y_pred=z, y_true=y)
loss

0.4676596264285731

In [14]:
weight = W1.item()
bias = b1.item()

In [15]:
weight

1.764052345967664

In [16]:
bias

0.4001572083672233

In [17]:
def gradientDescent(alpha=0.01, epochs=5):
    w = weight
    b = bias
    n = len(data)
    for _ in range(epochs):
        dw = (1/n)*np.sum(loss*data)
        db = (1/n)*np.sum(loss)
        w -= alpha * dw
        b -= alpha * db
        print(f'Epoch : {_+1} | weight : {w} | bias : {b}')
        
    return w, b

In [18]:
w, b = gradientDescent()

Epoch : 1 | weight : 1.764683167764032 | bias : 0.3996895487407947
Epoch : 2 | weight : 1.7653139895604 | bias : 0.3992218891143661
Epoch : 3 | weight : 1.765944811356768 | bias : 0.39875422948793754
Epoch : 4 | weight : 1.766575633153136 | bias : 0.39828656986150895
Epoch : 5 | weight : 1.767206454949504 | bias : 0.39781891023508037
